version: '3.6'

services:
  db:
    build:
      context: .
      dockerfile: insecure-db.Dockerfile
    image: demo_db:1.0
    restart: always

  app:
    image: cyberark/demo-app
    restart: always
    ports:
    - "8081:8080"
    environment:
      DB_URL: postgresql://db:5432/demo_db
      DB_USERNAME: demo_service_account
      DB_PASSWORD: YourStrongSAPassword 
      DB_PLATFORM: postgres
    depends_on: [ db ]
