version: '2'

services:
  db:
    image: demo_db:1.0
    restart: always

  app:
    build:
      context: .
      dockerfile: secure-app.Dockerfile
    image: cyberark/secure-demo-app:1.0
    restart: always
    ports:
    - "8082:8080"
    environment:
      DB_URL: postgresql://db:5432/demo_db
      DB_PLATFORM: postgres
      DB_USERNAME: 
      DB_PASSWORD:  
      CONJUR_APPLIANCE_URL: http://conjur 
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: host/frontend/frontend-01
      CONJUR_AUTHN_API_KEY: ${frontend_api}
    depends_on: [ db ]
